[build-system]
requires = ["uv_build>=0.9.6,<1.0"]
build-backend = "uv_build"

[project]
name = "sdf_pipeline"
version = "1.0.0"
requires-python = ">=3.11,<3.13"
dependencies = ["pydantic == 2.11.5", "pytest == 8.3.5"]

[project.optional-dependencies]
# FIXME: Don't force numpy major version as soon as https://github.com/IUPAC-InChI/InChI/issues/35 is resolved.
invariance-tests = ["rdkit == 2023.9.6", "numpy < 2.0.0"]

[tool.pytest.ini_options]
testpaths = ["tests/test_executable", "tests/test_meta"]
addopts = "-v"
