name: InChI Continuous Integration

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test_glibc_gcc:
    runs-on: ubuntu-24.04
    container: python:3.12

    steps:
      - uses: actions/checkout@v6

      - id: setup
        run: ./.devcontainer/post_create_commands.sh

      - name: Run unit tests
        run: cd CMake_build/full_build/INCHI-1-TEST/tests/test_unit && ctest --output-on-failure

      - name: Run executable tests
        run: pytest INCHI-1-TEST/tests/test_executable

      - name: Run multithreading test
        run: python INCHI-1-TEST/tests/test_library/test_multithreading.py
        timeout-minutes: 1

      - uses: ./.github/actions/regression_tests
        with:
          artifact-name: regression-test-results_glibc_gcc

      - uses: ./.github/actions/invariance_tests
        with:
          artifact-name: invariance-test-results_glibc_gcc


  test_musl_gcc:
    runs-on: ubuntu-24.04
    container: alpine:latest

    steps:
      - name: Install build and test environment
        run: |
          apk add bash git musl-dev gcc g++ make python3 py-pip cmake

      # We need to install git before checking out the repository.
      # Otherwise, the repository will be downloaded using the GitHub REST API instead of git.
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Install test dependencies
        run: uv sync --directory ./INCHI-1-TEST

      - id: build
        run: ./INCHI-1-TEST/build_with_cmake.sh all

      - name: Run unit tests
        run: cd CMake_build/full_build/INCHI-1-TEST/tests/test_unit && ctest --output-on-failure

      - name: Run executable tests
        if: ${{ !cancelled() && steps.build.outcome == 'success' }}
        run: uv run --directory ./INCHI-1-TEST -m pytest tests/test_executable

      - name: Run multithreading test
        if: ${{ !cancelled() && steps.build.outcome == 'success' }}
        run: uv run --directory ./INCHI-1-TEST tests/test_library/test_multithreading.py
        timeout-minutes: 1

      - uses: ./.github/actions/regression_tests
        if: ${{ !cancelled() && steps.build.outcome == 'success' }}
        with:
          artifact-name: regression-test-results_musl_gcc

      # FIXME: We don't run invariance test on alpine yet because of difficulties with RDKit installation.
